spring:
  docker:
    compose:
      lifecycle-management: start_only

  datasource:
    url: "jdbc:postgresql://localhost:5432/test"
    username: postgres
    password: 1954623790
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: trace
